parameters:
    security.authentication.provider.dao.class: eZ\Publish\Core\MVC\Symfony\Security\Authentication\RepositoryAuthenticationProvider
    security.authentication.provider.anonymous.class: eZ\Publish\Core\MVC\Symfony\Security\Authentication\AnonymousAuthenticationProvider
    ezpublish.security.user_provider.class: eZ\Publish\Core\MVC\Symfony\Security\User\Provider
    ezpublish.security.voter.core.class: eZ\Publish\Core\MVC\Symfony\Security\Authorization\Voter\CoreVoter
    ezpublish.security.voter.value_object.class: eZ\Publish\Core\MVC\Symfony\Security\Authorization\Voter\ValueObjectVoter
    ezpublish.security.authentication_provider.basic.class: eZ\Publish\Core\MVC\Symfony\Security\Authentication\BasicAuthProvider
    ezpublish.security.controller.class: eZ\Publish\Core\MVC\Symfony\Controller\SecurityController
    security.http_utils.class: eZ\Publish\Core\MVC\Symfony\Security\HttpUtils
    ezpublish.user.identity.class: eZ\Publish\Core\MVC\Symfony\Security\User\Identity
    ezpublish.user.hash_generator.class: eZ\Publish\Core\MVC\Symfony\Security\User\HashGenerator
    ezpublish.user.identity_definer.role_id.class: eZ\Publish\Core\MVC\Symfony\Security\User\IdentityDefiner\Role

services:
    ezpublish.security.user_provider:
        class: %ezpublish.security.user_provider.class%
        arguments: [@ezpublish.api.repository.lazy]

    ezpublish.security.authentication_provider.basic:
        class: %ezpublish.security.authentication_provider.basic.class%
        abstract: true
        arguments:
            - @ezpublish.api.repository.lazy
            - @security.user_checker
            - ~     # Provider-shared Key
            - %security.authentication.hide_user_not_found%

    ezpublish.security.voter.core:
        class: %ezpublish.security.voter.core.class%
        arguments: [@ezpublish.api.repository.lazy]
        public: false
        tags:
            - { name: security.voter }

    ezpublish.security.voter.value_object:
        class: %ezpublish.security.voter.value_object.class%
        arguments: [@ezpublish.api.repository.lazy]
        public: false
        tags:
            - { name: security.voter }

    ezpublish.security.controller:
        class: %ezpublish.security.controller.class%
        arguments: [@templating, @ezpublish.config.resolver, @?form.csrf_provider]
        calls:
            - [setRequest, [@?request=]]

    ezpublish.user.identity:
        class: %ezpublish.user.identity.class%

    ezpublish.user.hash_generator:
        class: %ezpublish.user.hash_generator.class%
        argugments: [[]]
        calls:
            - [setIdentity, [@ezpublish.user.identity]]

    ezpublish.user.identity_definer.role_id:
        class: %ezpublish.user.identity_definer.role_id.class%
        arguments: [@ezpublish.api.repository]
        tags:
            - { name: ezpublish.identity_definer }
