parameters:
    ezpublish_legacy.security.login_cleanup_listener.class: eZ\Publish\Core\MVC\Legacy\Security\Firewall\LoginCleanupListener
    ezpublish_legacy.security_mapper.class: eZ\Bundle\EzPublishLegacyBundle\LegacyMapper\Security

services:
    ezpublish_legacy.security.login_cleanup_listener:
        class: %ezpublish_legacy.security.login_cleanup_listener.class%
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.security_mapper:
        class: %ezpublish_legacy.security_mapper.class%
        arguments: [@ezpublish.api.repository, @ezpublish.config.resolver]
        tags:
            - { name: kernel.event_subscriber }
